- name: Upgrade python pip dependencies
  pip: 
    name: pip
    state: latest
    #executable: pip3
  become: true
- name: Install openshift python dependencies
  pip: 
    name: openshift
    state: latest
    #executable: pip3
  become: true
- name: Get computate-zookeeper deployment
  get_url: 
    url: https://raw.githubusercontent.com/computate/computate-zookeeper/master/openshift-computate-zookeeper.yaml
    dest: /tmp/openshift-computate-zookeeper.yaml
- name: Install computate-zookeeper on OpenShift
  k8s: 
    state: present
    host: "{{COMPUTATE_ZOOKEEPER_HOST}}"
    api_key: "{{COMPUTATE_ZOOKEEPER_TOKEN}}"
    namespace: "{{COMPUTATE_ZOOKEEPER_NAMESPACE}}"
    src: "/tmp/openshift-computate-zookeeper.yaml"

