---
- name: Get backup site access token
  shell: curl -X POST -u "{{AUTH_RESOURCE}}:{{AUTH_SECRET}}" -d "grant_type=client_credentials" "{{AUTH_URL}}/realms/{{AUTH_REALM}}/protocol/openid-connect/token"
  register: AUTH_TOKEN
- name: Request school data
  shell: "curl -X GET -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL}}/api/school?rows=0'"
  register: REQUEST_DATA
- name: Create the data vault directory
  file: 
    path: "{{COMPUTATE_SCOLAIRE_BACKUP_DIR}}/{{ansible_date_time.weekday}}"
    state: directory
    owner: "{{USER_NAME}}"
    group: "{{USER_NAME}}"
- name: Request and encrypt the response data
  shell: "curl -X GET -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL}}/api/school?rows=100&start=0' | ansible-vault encrypt_string --vault-password-file '/usr/local/src/computate/ansible/bin/echo-vault-password.sh' | sed 1d | tr -d ' ' > '{{COMPUTATE_SCOLAIRE_BACKUP_DIR}}/{{ansible_date_time.weekday}}/school'"
#- name: Write encrypted response data to the vault  
#  copy: 
#    content: "{{VAULT_DATA.stdout}}"
#    dest: "{{COMPUTATE_SCOLAIRE_BACKUP_DIR}}/{{ansible_date_time.weekday}}/school"

