---
- name: Get backup site access token
  shell: curl -X POST -u "{{AUTH_RESOURCE}}:{{AUTH_SECRET}}" -d "grant_type=client_credentials" "{{AUTH_URL}}/realms/{{AUTH_REALM}}/protocol/openid-connect/token"
  register: AUTH_TOKEN
- name: Create the data vault directory
  file: 
    path: "{{COMPUTATE_SCOLAIRE_BACKUP_DIR}}/{{ansible_date_time.weekday}}"
    state: directory
    owner: "{{USER_NAME}}"
    group: "{{USER_NAME}}"
- name: Request {{DATA_NAME_VAR}} data
  shell: "curl -X GET -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL}}{{DATA_URI}}?rows=0'"
  register: REQUEST_DATA
- name: Request and encrypt the {{DATA_NAME_VAR}} response data
  shell: "export VAULT_PASSWORD='{{VAULT_PASSWORD}}' && curl -X GET -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' '{{COMPUTATE_SCOLAIRE_SITE_BASE_URL}}{{DATA_URI}}?fl=saves&rows=100&start={{item}}' | ansible-vault encrypt_string --vault-password-file '/usr/local/src/computate/ansible/bin/echo-vault-password.sh' | sed 1d | tr -d ' ' > '{{COMPUTATE_SCOLAIRE_BACKUP_DIR}}/{{ansible_date_time.weekday}}/{{DATA_NAME_VAR}}{{item}}'"
  with_sequence: "start=0 end={{(REQUEST_DATA.stdout | from_json).foundNum}} stride=100"

