# Before doing a restore, you may want to clear the database and search engine of the destination: 
# Solr Pod: 
# curl -X POST -d '<delete><query>*:*</query></delete>' http://localhost:8080/solr/clinic/update?commitWithin=1000&overwrite=true&wt=xml
# Postgres Pod: 
# psql clinic -c 'delete from a; delete from d; delete from c;'
---
- name: Decrypt and import the {{DATA_NAME_VAR}} data
  shell: "export VAULT_PASSWORD='{{VAULT_PASSWORD}}' && cat '{{item}}' | ansible-vault decrypt --vault-password-file '/usr/local/src/computate/ansible/bin/echo-vault-password.sh' | curl -X PUT -H 'Authorization: Bearer {{(AUTH_TOKEN.stdout | from_json).access_token}}' -H 'Content-Type: application/json' -d @- '{{COMPUTATE_MEDICALE_SITE_BASE_URL_ENUS}}{{DATA_URI}}/import?var=refresh:false' && sleep 5"
  with_fileglob: 
    - "{{COMPUTATE_MEDICALE_RESTORE_DIR_ENUS}}/{{DATA_NAME_VAR}}*"

