#- name: Install {{COMPUTATE_SCOLAIRE_NAME}} dependencies
#  package:
#    name: [git,java-1.8.0-openjdk-devel]
#  become: yes
- name: Create the {{COMPUTATE_SCOLAIRE_NAME}} source directory {{COMPUTATE_SCOLAIRE_SRC}}
  file:
    name: "{{COMPUTATE_SCOLAIRE_SRC}}"
    state: directory
    owner: "{{USER_NAME}}"
    group: "{{USER_NAME}}"
  become: yes
- name: Clone the {{COMPUTATE_SCOLAIRE_NAME}} source code
  git:
    repo: "{{COMPUTATE_SCOLAIRE_REPO}}"
    dest: "{{COMPUTATE_SCOLAIRE_SRC}}"
- name: Create the {{COMPUTATE_SCOLAIRE_NAME}} systemd service {{COMPUTATE_SCOLAIRE_SYSTEMD}}. 
  template:
    src: computate_scolaire_service.j2
    dest: "{{COMPUTATE_SCOLAIRE_SYSTEMD}}"
  become: yes
- name: Create the {{COMPUTATE_MEDICALE_NAME}} config dir.
  file: 
    name: "{{COMPUTATE_SCOLAIRE_SRC}}/config"
    state: directory
    owner: "{{USER_NAME}}"
    group: "{{USER_NAME}}"
- name: Create the {{COMPUTATE_SCOLAIRE_NAME}} default frFR config. 
  template:
    src: computate_scolaire_frFR_config.config.j2
    dest: "{{COMPUTATE_SCOLAIRE_SRC}}/config/computate-scolaire.config"
  become: yes
- name: Create the {{COMPUTATE_SCOLAIRE_NAME}} enUS config. 
  template:
    src: computate_scolaire_config_enUS.config.j2
    dest: "{{COMPUTATE_SCOLAIRE_SRC}}/config/computate-scolaire-enUS.config"
  become: yes
- name: Reload the services. 
  systemd:
    daemon_reload: yes
  become: yes
- name: Start and enable the {{COMPUTATE_SCOLAIRE_NAME}} service. 
  service:
    name: "{{COMPUTATE_SCOLAIRE_SERVICE}}"
    enabled: yes
    state: restarted
  become: yes
- name: Create frFR database user
  postgresql_user: 
    name: "{{COMPUTATE_SCOLAIRE_DB_USER_FRFR}}"
    password: "{{COMPUTATE_SCOLAIRE_DB_PASSWORD_FRFR}}"
    login_unix_socket: /tmp
  become: true
  become_user: postgres
- name: Create frFR database
  postgresql_db: 
    name: "{{COMPUTATE_SCOLAIRE_DB_NAME_FRFR}}"
    owner: "{{COMPUTATE_SCOLAIRE_DB_USER_FRFR}}"
    login_unix_socket: /tmp
  become: true
  become_user: postgres
- name: Create enUS database user
  postgresql_user: 
    name: "{{COMPUTATE_SCOLAIRE_DB_USER_ENUS}}"
    password: "{{COMPUTATE_SCOLAIRE_DB_PASSWORD_ENUS}}"
    login_unix_socket: /tmp
  become: true
  become_user: postgres
- name: Create enUS database
  postgresql_db: 
    name: "{{COMPUTATE_SCOLAIRE_DB_NAME_ENUS}}"
    owner: "{{COMPUTATE_SCOLAIRE_DB_USER_ENUS}}"
    login_unix_socket: /tmp
  become: true
  become_user: postgres

