- name: Install postgres persistent volume claim on OpenShift
  k8s: 
    state: present
    name: postgres-persistent-volume-claim
    host: "{{POSTGRES_HOST}}"
    api_key: "{{POSTGRES_TOKEN}}"
    namespace: "{{POSTGRES_NAMESPACE}}"
    definition: "{{ lookup('template', 'postgres_persistent_volume_claim.yml.j2') }}"
- name: Install postgres deployment config on OpenShift
  k8s: 
    state: present
    name: postgres
    host: "{{POSTGRES_HOST}}"
    api_key: "{{POSTGRES_TOKEN}}"
    namespace: "{{POSTGRES_NAMESPACE}}"
    definition: "{{ lookup('template', 'postgres_deployment_config.yml.j2') }}"

