- name: Install redhat-sso keystore secret on OpenShift
  k8s: 
    state: present
    name: redhat-sso-keystore
    host: "{{REDHAT_SSO_HOST}}"
    api_key: "{{REDHAT_SSO_TOKEN}}"
    namespace: "{{REDHAT_SSO_NAMESPACE}}"
    definition: "{{ lookup('template', 'redhat_sso_keystore.yml.j2') }}"
- name: Install redhat-sso persistent volume claim on OpenShift
  k8s: 
    state: present
    name: redhat-sso-persistent-volume-claim
    host: "{{REDHAT_SSO_HOST}}"
    api_key: "{{REDHAT_SSO_TOKEN}}"
    namespace: "{{REDHAT_SSO_NAMESPACE}}"
    definition: "{{ lookup('template', 'redhat_sso_persistent_volume_claim.yml.j2') }}"
- name: Install redhat-sso deployment config on OpenShift
  k8s: 
    state: present
    name: redhat-sso
    host: "{{REDHAT_SSO_HOST}}"
    api_key: "{{REDHAT_SSO_TOKEN}}"
    namespace: "{{REDHAT_SSO_NAMESPACE}}"
    definition: "{{ lookup('template', 'redhat_sso_deployment_config.yml.j2') }}"
- name: Install redhat-sso service on OpenShift
  k8s: 
    state: present
    name: redhat-sso
    host: "{{REDHAT_SSO_HOST}}"
    api_key: "{{REDHAT_SSO_TOKEN}}"
    namespace: "{{REDHAT_SSO_NAMESPACE}}"
    definition: "{{ lookup('template', 'redhat_sso_service.yml.j2') }}"

