---
- name: Check for GITHUB_TOKEN var
  fail: 
    msg: "Make sure you have correctly configured a GITHUB_TOKEN: '...' in your ansible vault. You will want to configure a Github token with 'admin:org' and 'repo' scopes (https://github.com/settings/tokens). "
  when: GITHUB_TOKEN is not defined
  tags: github_token
- name: Check for GITHUB_ORG var
  fail: 
    msg: "Make sure you have correctly configured a GITHUB_ORG: '...' in your ansible vault. This should be a Github organization that your user and token have access to (https://github.com/organizations/plan). "
  when: GITHUB_ORG is not defined
  tags: github_org
- name: "Get Github org {{ GITHUB_ORG }}"
  uri: 
    url: "https://api.github.com/orgs/{{ GITHUB_ORG }}"
    return_content: true
    headers: 
      Authorization: "token {{ GITHUB_TOKEN }}"
  ignore_errors: true
  register: GITHUB_ORG_JSON
  tags: github_org
- name: Check Github token
  fail: 
    msg: "Make sure you have correctly configured a GITHUB_TOKEN: '...' in your ansible vault. You will want to configure a Github token with 'admin:org' and 'repo' scopes (https://github.com/settings/tokens). You are using GITHUB_TOKEN: {{ GITHUB_TOKEN }}"
  when: GITHUB_ORG_JSON.failed and (GITHUB_ORG_JSON.status is not defined or GITHUB_ORG_JSON.status == 401)
  tags: github_token
- name: Check for Github org
  fail: 
    msg: "Make sure you have correctly configured a GITHUB_ORG: '...' in your ansible vault. This should be a Github organization that your user and token have access to (https://github.com/organizations/plan). You are using GITHUB_ORG: {{ GITHUB_ORG }}"
  when: GITHUB_ORG_JSON.failed and GITHUB_ORG_JSON.status == 404
  tags: github_org
- name: "Get Github repo {{ GITHUB_REPO }}"
  uri: 
    url: "https://api.github.com/repos/{{ GITHUB_ORG }}/{{ GITHUB_REPO }}"
    return_content: true
    headers: 
      Authorization: "token {{ GITHUB_TOKEN }}"
  ignore_errors: true
  register: GITHUB_REPO_JSON
  tags: github_repo
- name: "Fork Github repo {{ GITHUB_REPO }}"
  uri: 
    url: "https://api.github.com/repos/computate-org/computate-org-school/forks?organization={{ GITHUB_ORG | urlencode() }}"
    method: POST
    return_content: true
    headers: 
      Authorization: "token {{ GITHUB_TOKEN }}"
  when: GITHUB_REPO_JSON.failed and GITHUB_REPO_JSON.status == 404
  tags: github_repo
- name: Check for Github repo
  fail: 
    msg: "Make sure you have correctly configured a GITHUB_REPO: '...' in your ansible vault. This should be a Github repository in your Github organization that your user and token have access to. You are using GITHUB_REPO: {{ GITHUB_REPO }}"
  when: GITHUB_REPO_JSON.failed and GITHUB_REPO_JSON.status == 404
  tags: github_repo

####################################
# OpenShift Cluster Administration #
####################################

- name: Create issue to setup OpenShift cluster
  include_role: 
    name: computate_org_school_issue
  vars: 
    ISSUE_LABEL: setup_openshift_cluster
    ISSUE_TITLE: Setup OpenShift cluster
    ISSUE_BODY: |
      Red Hat employees can obtain a free OpenShift cluster with 4GiB RAM and 10 GiB storage with their people manager approval here: 

      https://employee.openshift.com/register/employee/introduction

      You may also obtain an OpenShift cluster by registering for a course that provisions a temporary OpenShift environment. 
  tags: 
    - issue_label
    - issue_label_1

#########################
# OpenShift Development #
#########################

- name: Create issue to install ansible locally
  include_role: 
    name: computate_org_school_issue
  vars: 
    ISSUE_LABEL: install_ansible_locally
    ISSUE_TITLE: Install Ansible Locally
    ISSUE_BODY: |
      The installation of the project for both development and production in containers is completely automated with Ansible.
      Begin by installing both the ansible and python3 packages.
      
      ```bash
      sudo yum install -y ansible python3 python3-pip
      sudo pip3 install psycopg2
      ```
      
      If psycopg2 does not install, run:
      
      ```bash
      sudo pip3 install psycopg2-binary
      ```
      
      ## Ansible on older operating systems.
      
      If you have an older operating system that does not yet support python3, you may struggle to deploy the application on OpenShift in the cloud. The OpenShift Ansible modules seem to require python3 as the system library, so I recommend updating your operating system to something more recent, for example CentOS8 or RHEL8.
      
      On older operating systems, to deploy the development applications you might want to configure ansible for python2.
      
      To deploy to OpenShift, you will want to configure ansible to point to python3.
      
      You might update your ansible configuration like this to make it work:
      
      ```
      sudo vim /etc/ansible/ansible.cfg
      ```
      
      ```
      [defaults]
      interpreter_python=/usr/bin/python3
      ```
      
      Your dependencies might be different on an older operating system.
      
      ```bash
      sudo yum install -y ansible python python-pip
      sudo pip install psycopg2
      ```

      ## Setup ssh on your computer for ansible to connect

      For ansible to run commands, it needs to be able to ssh and run commands as sudo. For that, make sure the sshd service is started and enabled after a reboot. Also test an ssh connection to your hostname to make sure the host is accepted. 

      ```bash
      systemctl status sshd
      sudo systemctl start sshd
      sudo systemctl enable sshd
      systemctl status sshd
      ssh $HOSTNAME
      exit
      ```

      
      ## Ansible training.
      
      For training on ansible and automation, I recommend the following Red Hat course.
      By completing the course and taking the exam, you can be a Red Hat Certified Specialist in Ansible Automation.
      
      https://www.redhat.com/en/services/training/do407-automation-ansible-i
  tags: 
    - issue_label
    - issue_label_2

- name: "Create issue to clone computate-org-school repo"
  include_role: 
    name: computate_org_school_issue
  vars: 
    ISSUE_LABEL: clone_computate_org_school_repo
    ISSUE_TITLE: "Clone the {{ GITHUB_REPO }} git repository"
    ISSUE_BODY: |
      Create a directory for the {{ GITHUB_REPO }} repository with the included ansible scripts to setup issues in Github for the organization.
      
      ```bash
      sudo install -d -o $USER -g $USER {{ REPO_PATH }}
      ```

      Clone the git repository into the new directory. 

      ```bash
      git clone git@github.com:{{ GITHUB_ORG }}/{{ GITHUB_REPO }}.git {{ REPO_PATH }}
      ```
      
      Create a directory for your development inventory.
      
      ```bash
      install -d {{ REPO_PATH }}/inventories/$USER-$HOSTNAME
      ```
      
      Create a hosts file for your development inventory. Add your hostname to each of the following host groups so that ansible can run each of these playbooks on your host. 
      
      ```bash
      echo '
      [computate_org_school]
      {{ HOST_NAME }}

      [computate_postgres]
      {{ HOST_NAME }}

      [computate_zookeeper]
      {{ HOST_NAME }}

      [computate_solr]
      {{ HOST_NAME }}

      [computate_certbot]
      {{ HOST_NAME }}

      [computate_scolaire]
      {{ HOST_NAME }}

      [computate_scolaire_login]
      {{ HOST_NAME }}

      [computate_scolaire_refresh]
      {{ HOST_NAME }}

      [computate_scolaire_backup]
      {{ HOST_NAME }}

      [computate_scolaire_restore]
      {{ HOST_NAME }}
      ' > {{ REPO_PATH }}/inventories/$USER-$HOSTNAME/hosts
      ```
  tags: 
    - issue_label
    - issue_label_3

- name: "Create issue to create an ansible vault"
  include_role: 
    name: computate_org_school_issue
  vars: 
    ISSUE_LABEL: create_local_dev_ansible_vault
    ISSUE_TITLE: "Create an ansible vault for your local development"
    ISSUE_BODY: |
      ### Create an ansible vault for your local development.
      
      Create and edit an encrypted ansible vault with a password for the host secrets for your development inventory.
      
      ```bash
      ansible-vault create {{ REPO_PATH }}/inventories/$USER-$HOSTNAME/host_vars/$HOSTNAME/vault
      ansible-vault edit {{ REPO_PATH }}/inventories/$USER-$HOSTNAME/host_vars/$HOSTNAME/vault
      ```
      
      The contents of the vault will contain the secrets needed to override any default values you want to change in the computate-scolaire defaults defined here.
      
      https://github.com/computate/computate/blob/master/ansible/roles/computate_scolaire/defaults/main.yml
      
      There are descriptions for each of the fields.
      There are several sections of fields, including:
      
      - computate-scolaire system defaults
      - Ansible defaults
      - Zookeeper defaults
      - Solr defaults
      - PostgreSQL defaults
      - computate-medical global defaults
      - computate-scolaire US English defaults
      - SMTP defaults
      - OpenID Connect auth server defaults
      - SSL/TLS defaults

      Here is an example of the contents of the ansible vault for local development: 

      ```yaml
      {{ lookup('url', 'https://raw.githubusercontent.com/computate/computate/master/ansible/roles/computate_scolaire/defaults/main.yml', split_lines=false) }}
      ```

      Look for values to override, especially those like this: "...". 
  tags: 
    - issue_label
    - issue_label_4

- name: "Create issue to clone computate repo"
  include_role: 
    name: computate_org_school_issue
  vars: 
    ISSUE_LABEL: clone_computate_repo
    ISSUE_TITLE: "Clone the computate git repository"
    ISSUE_BODY: |
      Create a directory for the computate repository with the included ansible scripts for installing the school applications for development and in OpenShift.
      
      ```bash
      sudo install -d -o $USER -g $USER /usr/local/src/computate
      ```

      Clone the git repository into the new directory. 

      ```bash
      git clone git@github.com:computate/computate.git /usr/local/src/computate
      ```
  tags: 
    - issue_label
    - issue_label_5

# Task to decide the project/namespace name
# Task to deploy PostgreSQL database (default OpenShift app)
# Task to deploy Zookeeper cluster manager (custom container from quay.io)
# Task to deploy Apache Solr Search Engine (custom container from quay.io)
# Task to deploy school application (s2i image)

#############
# SSO Admin #
#############
# Task to deploy Red Hat SSO (default OpenShift app)
# Task to configure SSO Realm
# Task to configure SSO client
# Task to configure client service account and roles
# Task to configure client redirect URIs
# Task to configure client confidential access 
# Task to configure client roles (SiteAdmin, SiteManager)
# Task to configure your own user in SSO
# Task to request access from SSO admin for roles (SiteAdmin or SiteManager)

#####################
# Application Admin #
#####################
# Import default school data into the application
# Task to create school in the application
# Task to create the school year in the application
# Task to create the school ages in the application
# Task to create the school block times in the application
# Task to enroll some students 

######################
# HTML App Dev tasks #
######################
# Task to customize a homepage
# Task to customize a enrollment form
# 
