- name: Install {{ZOOKEEPER_NAME}} dependencies. 
  package:
    name: [git,java-1.8.0-openjdk-devel,maven]
  become: yes
- name: Create the {{ZOOKEEPER_NAME}} source directory {{ZOOKEEPER_SRC}}. 
  file:
    name: "{{ZOOKEEPER_SRC}}"
    state: directory
    owner: "{{USER_NAME}}"
    group: "{{USER_NAME}}"
  become: yes
- name: Clone the {{ZOOKEEPER_NAME}} source code. 
  git:
    repo: "{{ZOOKEEPER_REPO}}"
    dest: "{{ZOOKEEPER_SRC}}"
    version: "{{ZOOKEEPER_TAG}}"
- name: Build the {{ZOOKEEPER_NAME}} application. 
  shell: mvn clean install -DskipTests
  args:
    chdir: "{{ZOOKEEPER_SRC}}"
    creates: "{{ZOOKEEPER_SRC}}/{{ZOOKEEPER_NAME}}-assembly/target/apache-{{ZOOKEEPER_NAME}}-{{ZOOKEEPER_VERSION}}-bin.tar.gz"
- name: Create the {{ZOOKEEPER_NAME}} install directory {{ZOOKEEPER_OPT}}. 
  file:
    name: "{{ZOOKEEPER_OPT}}"
    state: directory
    owner: "{{USER_NAME}}"
    group: "{{USER_NAME}}"
  become: yes
- name: Install {{ZOOKEEPER_NAME}} into the {{ZOOKEEPER_OPT}} install directory. 
  unarchive: 
    src: "{{ZOOKEEPER_SRC}}/{{ZOOKEEPER_NAME}}-assembly/target/apache-{{ZOOKEEPER_NAME}}-{{ZOOKEEPER_VERSION}}-bin.tar.gz"
    dest: "{{ZOOKEEPER_OPT}}"
    remote_src: yes
    extra_opts: [--strip-components=1]
- name: Create the {{ZOOKEEPER_NAME}} install directory {{ZOOKEEPER_OPT}}. 
  file:
    name: "{{ZOOKEEPER_OPT}}"
    state: directory
- name: Create the {{ZOOKEEPER_NAME}} config file {{ZOOKEEPER_CONF}}. 
  copy:
    dest: "{{ZOOKEEPER_CONF}}"
    content: |
      dataDir={{ZOOKEEPER_DATA}}
      clientPort={{ZOOKEEPER_CLIENT_PORT}}
      admin.serverPort={{ZOOKEEPER_CLIENT_PORT}}
- name: Create the {{ZOOKEEPER_NAME}} systemd service {{ZOOKEEPER_SYSTEMD}}. 
  copy:
    dest: "{{ZOOKEEPER_SYSTEMD}}"
    content: |
      [Unit]
      Description=An open source centralized cluster manager. 
      After=network.target

      [Service]
      Type=simple
      User={{USER_NAME}}
      Group={{USER_NAME}}
      WorkingDirectory={{ZOOKEEPER_OPT}}
      ExecStart={{ZOOKEEPER_OPT}}/bin/zkServer.sh start-foreground
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
  become: yes
- name: Reload the services. 
  systemd:
    daemon_reload: yes
  become: yes
- name: Start and enable the {{ZOOKEEPER_NAME}} service. 
  service:
    name: "{{ZOOKEEPER_SERVICE}}"
    enabled: yes
    state: started
  become: yes

