- name: Install computate-zookeeper on OpenShift
  k8s: 
    state: present
    host: "{{COMPUTATE_ZOOKEEPER_HOST}}"
    api_key: "{{COMPUTATE_ZOOKEEPER_TOKEN}}"
    namespace: "{{COMPUTATE_ZOOKEEPER_NAMESPACE}}"
    definition: "{{ lookup('template', 'computate_zookeeper_image_stream.yaml.j2') }}"

