#- name: Upgrade python pip dependencies
#  pip: 
#    name: pip
#    state: latest
#    #executable: pip3
#  become: true
#- name: Install openshift python dependencies
#  pip: 
#    name: openshift
#    state: latest
#    #executable: pip3
#  become: true
- name: Get computate-zookeeper deployment
  template: 
    src: computate-zookeeper-image-stream.yml
    dest: /tmp/computate-zookeeper-image-stream.yaml
- name: Install computate-zookeeper on OpenShift
  k8s: 
    state: present
    host: "{{COMPUTATE_ZOOKEEPER_HOST}}"
    api_key: "{{COMPUTATE_ZOOKEEPER_TOKEN}}"
    namespace: "{{COMPUTATE_ZOOKEEPER_NAMESPACE}}"
    src: "/tmp/computate-zookeeper-image-stream.yaml"

